### ISSUE TITLE
ImportErrorinstall 

### ISSUE THREAD

**Issue by dinos66** [dewe/gavagai-python#1]
Hello. 
I'm having a bit of trouble using gavagai and I hope you can help since all gavagai's requests seem to have been installed successfully and I can't seem to work out what's going on. I use windows7 with python 3.3. I've also tried it on two different pcs with the same setup and on another using windows 8. All the dependencies seem to be uptodate. Any ideas?

When running "from gavagai.client import GavagaiClient" I get the following error for windows7:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from gavagai.client import GavagaiClient
  File "C:\Python33\lib\site-packages\gavagai\client.py", line 4, in <module>
    from exceptions import GavagaiException, GavagaiHttpException
ImportError: No module named 'exceptions'

And this one on windows8:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from gavagai.client import GavagaiClient
  File "C:\Python33\lib\site-packages\gavagai\client.py", line 3, in <module>
    import requests
  File "C:\Python33\lib\site-packages\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:\Python33\lib\site-packages\requests\utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\Python33\lib\site-packages\requests\compat.py", line 7, in <module>
    from .packages import chardet
  File "C:\Python33\lib\site-packages\requests\packages\__init__.py", line 3, in <module>
    from . import urllib3
  File "C:\Python33\lib\site-packages\requests\packages\urllib3\__init__.py", line 16, in <module>
    from . import exceptions
ImportError: cannot import name exceptions

**Comment by dinos66** [comment]
My bad. I just noticed gavagai only supports python <3.

**Comment by dewe** [comment]
Thanks for trying it out. As you noticed, I haven't tested against Python 3+. I'll have a look at what's needed for supporting both versions. 

/Johan

**Comment by dinos66** [comment]
That would be excellent. I was really psyched to try out some of the features. ------------------------------- Dr. Konstantinos KonstantinidisPost-doctoral Research FellowInformation Technologies Institute,CERTHTel: +30 2311257720WWW: http://www.iti.gr/iti/people/Konstantinos_Konstantinidis.html Twitter: https://twitter.com/dinos66------------------------------- 


     On Thursday, May 14, 2015 6:15 PM, Johan Dewe <notifications@github.com> wrote:
   
 

 Thanks for trying it out. As you noticed, I haven't tested against Python 3+. I'll have a look at what's needed for supporting both versions. 

/Johan

**Comment by dewe** [comment]
Started a pull request, trying to resolve remaining issues: #2.

**Comment by dewe** [comment]
Now there's a new version 0.2.7, supporting Python 3.3 and 2.7.

**Comment by dinos66** [comment]
Thanks! I'll give it a whirl and get back to you.
